porsche: Switch to armv8-2a
* Fixes:
    error: Incorrect TARGET_2ND_ARCH_VARIANT, armv8-a. Use armv8-2a instead

Signed-off-by: ad1tyas1ngh <adityasingh1768@gmail.com>